name: cvsd
description: "Junk photo cleanser."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image: ^4.5.4
  onnxruntime: ^1.4.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model/model.onnx
    - assets/icon.png

